const data = [
  {
    id: "1",
    name: "Destop-1",
    price: 10.99,
    img: "",
    category: "desktop",
  },
  {
    id: "2",
    name: "Destop-2",
    price: 100,
    img: "",
    category: "desktop",
  },
  {
    id: "3",
    name: "Destop-3",
    price: 100,
    img: "",
    category: "desktop",
  },
  {
    id: "4",
    name: "Destop-4",
    price: 70.5,
    img: "",
    category: "desktop",
  },
  {
    id: "5",
    name: "Destop-5",
    price: 300,
    img: "",
    category: "desktop",
  },
  {
    id: "6",
    name: "Laptop-1",
    price: 350,
    img: "",
    category: "laptop",
  },
  {
    id: "7",
    name: "Laptop-2",
    price: 200.75,
    img: "",
    category: "laptop",
  },
  {
    id: "8",
    name: "Laptop-3",
    price: 20,
    img: "",
    category: "laptop",
  },
  {
    id: "9",
    name: "Laptop-4",
    price: 19.25,
    img: "",
    category: "laptop",
  },
  {
    id: "10",
    name: "Laptop-5",
    price: 19.25,
    img: "",
    category: "laptop",
  },
  {
    id: "11",
    name: "Monitor-1",
    price: 19.25,
    img: "",
    category: "monitor",
  },
  {
    id: "12",
    name: "Monitor-2",
    price: 19.25,
    img: "",
    category: "monitor",
  },
  {
    id: "13",
    name: "Monitor-3",
    price: 19.25,
    img: "",
    category: "monitor",
  },
  {
    id: "14",
    name: "Monitor-4",
    price: 19.25,
    img: "",
    category: "monitor",
  },
  {
    id: "15",
    name: "Monitor-5",
    price: 19.25,
    img: "",
    category: "monitor",
  },
  {
    id: "16",
    name: "UPS-1",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "17",
    name: "UPS-2",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "18",
    name: "UPS-3",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "19",
    name: "UPS-4",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "20",
    name: "UPS-1",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "21",
    name: "UPS-6",
    price: 13.0,
    img: "",
    category: "ups",
  },
  {
    id: "22",
    name: "Office-equipment-1",
    price: 13.0,
    img: "",
    category: "office-eq",
  },
  {
    id: "23",
    name: "Office-equipment-2",
    price: 13.0,
    img: "",
    category: "office-eq",
  },
  {
    id: "24",
    name: "Office-equipment-3",
    price: 13.0,
    img: "",
    category: "office-eq",
  },
  {
    id: "25",
    name: "Office-equipment-4",
    price: 13.0,
    img: "",
    category: "office-eq",
  },
  {
    id: "26",
    name: "Camera-1",
    price: 145.0,
    img: "",
    category: "camera",
  },
  {
    id: "27",
    name: "Camera-2",
    price: 136.0,
    img: "",
    category: "camera",
  },
  {
    id: "28",
    name: "Camera-3",
    price: 130.0,
    img: "",
    category: "camera",
  },
  {
    id: "29",
    name: "Camera-4",
    price: 153.0,
    img: "",
    category: "camera",
  },
  {
    id: "30",
    name: "Camera-5",
    price: 185.0,
    img: "",
    category: "camera",
  },
  {
    id: "31",
    name: "Gaming-1",
    price: 185.0,
    img: "",
    category: "gaming",
  },
  {
    id: "32",
    name: "Gaming-2",
    price: 185.0,
    img: "",
    category: "gaming",
  },
  {
    id: "33",
    name: "Gaming-3",
    price: 185.0,
    img: "",
    category: "gaming",
  },
  {
    id: "34",
    name: "Gaming-4",
    price: 185.0,
    img: "",
    category: "gaming",
  },
  {
    id: "35",
    name: "Gaming-5",
    price: 185.0,
    img: "",
    category: "gaming",
  },
];
export default data;
